In [1]:
import numpy as np

# Question 1

In [2]:
def Discriminant(x, mu, covariance, probability):
    x_mu = np.subtract(x, mu)                                   # x - mu 
    x_mu_t = np.transpose(x_mu)                                 # (x - mu)t
    covariance_inverse = np.linalg.inv(covariance)              # covariance ^ -1
    d = mu.shape[0]                                             # num of dimensions 
    det = np.linalg.det(covariance)                             # | covariance |
    # g(x):
    disc = -0.5 * np.dot(x_mu_t, np.dot(covariance_inverse, x_mu)) - (d / 2) * np.log(np.pi / 2) - 0.5 * np.log(det) + np.log(probability)
    return disc

# Question 2

In [3]:
def Mahalanobis_Distance(x, mu, covariance):
    x_mu = np.subtract(x, mu)                                   
    x_mu_t = np.transpose(x_mu)
    covariance_inverse = np.linalg.inv(covariance)
    distance = np.dot(x_mu_t, np.dot(covariance_inverse, x_mu))
    return distance

# Question 3

In [4]:
w1 = np.transpose([[-5.01, -8.12, -3.68],[-5.43, -3.48, -3.54], [1.08, -5.52, 1.66], 
               [0.86, -3.78, -4.11], [-2.67, 0.63, 7.39], [4.94, 3.29, 2.08], 
               [-2.51, 2.09, -2.59], [-2.25, -2.13, -6.94], [5.56, 2.86, -2.26], 
               [1.03, -3.33, 4.33]])
Pw1 = 0.8
Pw2 = 0.1
Pw3 = 0.1
print w1

[[-5.01 -5.43  1.08  0.86 -2.67  4.94 -2.51 -2.25  5.56  1.03]
 [-8.12 -3.48 -5.52 -3.78  0.63  3.29  2.09 -2.13  2.86 -3.33]
 [-3.68 -3.54  1.66 -4.11  7.39  2.08 -2.59 -6.94 -2.26  4.33]]


In [5]:
def mean(x):
    num_samples = x.shape[1]
    sum = np.transpose([np.sum(x, axis=1)])
    mean = (1.0/num_samples) * sum
    return mean

In [6]:
def covariance(x, mu):
    num_samples = x.shape[1]
    x_mu = np.subtract(x, mu)
    x_mu_t = np.transpose(x_mu)
    return (1.0/num_samples) * np.dot(x_mu, x_mu_t)

In [7]:
m = mean(w1)
c = covariance(w1, m)

In [11]:
Discriminant(w1, m, c, Pw1)

array([[-6.12838341, -5.20816068, -5.08098171, -4.9110998 , -3.88822708,
        -3.05176233, -3.87648891, -4.84504409, -3.22986198, -4.56113407],
       [-5.20816068, -5.55475565, -3.83308252, -4.24103898, -4.71170169,
        -3.50487701, -5.21528502, -5.11778332, -3.54739914, -3.84706005],
       [-5.08098171, -3.83308252, -5.90590044, -4.94333302, -4.16392611,
        -4.34963835, -2.98844527, -3.75151154, -4.20554684, -5.55877827],
       [-4.9110998 , -4.24103898, -4.94333302, -5.26280956, -3.0325491 ,
        -4.3418122 , -3.86320419, -4.87524746, -4.92050426, -4.3895455 ],
       [-3.88822708, -4.71170169, -4.16392611, -3.0325491 , -7.39845649,
        -4.66110454, -5.08331042, -3.3080926 , -3.36564518, -5.16813086],
       [-3.05176233, -3.50487701, -4.34963835, -4.3418122 , -4.66110454,
        -5.8707332 , -4.55400416, -4.00219647, -5.78507582, -4.65993999],
       [-3.87648891, -5.21528502, -2.98844527, -3.86320419, -5.08331042,
        -4.55400416, -6.06324004, -5.13184399